### ISSUE TITLE
Pin doesn't work in obsidian v1.9.9

### ISSUE THREAD

**Issue by SolitaryAnimal** [verocloud/obsidian-mindmap-nextgen#78]
- System: Windows11 22H2
- Obsidian version: v1.9.9
- Obsidian installer version: v1.0.0
- Mind Map NextGen version: 1.2.0

Even if I have the pin turned on, the mind map will change as the document changes.

**Comment by AdrianSimionov** [comment]
@Black-Spree Is the behavior different using Obsidian version 1.1.9? I would highly appreciate if you could describe, from your perspective, the expected behavior of the pin function.

I have a feeling in this case it is just working as coded, and with not much documentation from our side, we might have messed it up.

@MasterTuto Can you please describe your understanding of the pin function, regardless of the Obsidian version? I want to see if we are aligned with user's expectations and if our documentation is clear and concise.

Next, we will decide which approach to take in regards to this issue.

**Comment by Black-Spree** [comment]
> 

Sorry, I didn't install this plugin in versions prior to obsidian v.1.9.9.

My expected behavior for the pin function is as described in the readme:
> Allows you to pin the Mind Map preview pane to the current note so that you can select other notes with the current Mind Map remaining in place.

**Comment by AdrianSimionov** [comment]
I can reproduce it myself too, it seems the "Pin" functionality does not work.

As soon as the .md file is changing, the rendered diagram is changing as well.

**Comment by james-tindal** [comment]
So the expected behaviour is...?
When pinned, the tab stays open, always displaying the same diagram.
When unpinned, which of these is the correct behaviour?
1. On file change: Tab closes.
2. On file change: Tab stays open but the displayed diagram changes

**Comment by james-tindal** [comment]
Perhaps we want to be able to open multiple tabs with a different mindmap in each?

**Comment by james-tindal** [comment]
Should the pinned mind map update when the document it's based on is edited, or never update at all?

**Comment by AdrianSimionov** [comment]
Right now, my understanding is that we have only one rendering view for a mindmap, and changing the active .md file will render the content of the active .md file.

The expected behavior of the "pin" feature would be that once the mindmap rendered view becomes "pinned", it updates based only on the current .md file which generated it, and it does not update based on the active .md file anymore.

**Comment by AdrianSimionov** [comment]
@james-tindal Is this issue fixed by PR #83 ?

**Comment by james-tindal** [comment]
The behaviour in the current main branch is:
+ When pinned, the pin icon replaces the close tab cross.
+ When pinned, the mindmap does not update at all. PR #86 makes a pinned tab only update based on the document it is pinned to. I really should have put this #83 before I pushed it.

**Comment by AdrianSimionov** [comment]
I am a bit hesitant about "When pinned, the pin icon replaces the close tab cross.". Doing it by default feel like taking a feature when giving one.

Let's change to:

When pinned, the close icon remains there, but the pin icon is also added to denote the tab is pinned. Once pinned, the tab should update only based on changes to the .md which pinned it.

When unpinned, the pin icon is removed and the mindmap starts rendering based on the active tab content.

**Comment by james-tindal** [comment]
It was the default behaviour when using Obsidian's pinning feature. Will fix.
